security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: [ROLE_STUDENT, ROLE_TEACHER]
        ROLE_SUPER_ADMIN: [ROLE_TEACHER]

    providers:
       in_memory:
            memory:
                users:
                    Prof:
                        password: pass
                        roles: ROLE_TEACHER
                    Eleve:
                        password: pass
                        roles: ROLE_STUDENT

    firewalls:
        main:
            pattern : ^/
            anonymous: ~
            provider:  in_memory
            form_login:
                login_path: /home/login
                check_path: /home/login_check
                username_parameter: 'user[username]'
                password_parameter: 'user[password]'
                success_handler: redirect.after.login

    access_control:
        - { path: ^/dashboard, roles: [ROLE_TEACHER, ROLE_STUDENT] }
        - { path: ^/dashboard-teacher, roles: ROLE_TEACHER }
        - { path: ^/dashboard-student, roles: ROLE_STUDENT }
