security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: [ROLE_STUDENT, ROLE_TEACHER]
        ROLE_SUPER_ADMIN: [ROLE_TEACHER]

    providers:
        my_provider:
            entity:
                class: UserBundle:User
                property: username
    firewalls:
        main:
            pattern : ^/
            anonymous: true
            provider:  my_provider
            form_login:
                login_path: /home/login
                check_path: login_check
                username_parameter: 'user[username]'
                password_parameter: 'user[password]'
                success_handler: redirect.after.login
            logout:
                path: /home/logout
                target: /home/login
    access_control:
        - { path: ^/dashboard, roles: [ROLE_TEACHER, ROLE_STUDENT] }
        - { path: ^/dashteacher, roles: ROLE_TEACHER }
        - { path: ^/dashstudent, roles: ROLE_STUDENT }
