security:
    encoders:
        UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN: [ROLE_STUDENT, ROLE_TEACHER]
        ROLE_SUPER_ADMIN: [ROLE_TEACHER]

    providers:
        my_provider:
            id: fos_user.user_provider.username
    firewalls:
        main:
            anonymous: true
            provider:  my_provider
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                success_handler: redirect.after.login
            logout:
                path:  fos_user_security_logout
                target: /login
            remember_me:
                key: %secret%
    access_control:
        - { path: ^/dashboard, roles: [ROLE_TEACHER, ROLE_STUDENT] }
        - { path: ^/dashteacher, roles: ROLE_TEACHER }
        - { path: ^/dashstudent, roles: ROLE_STUDENT }
