SpljBundle\Entity\Article:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        userId:
            type: integer
            column: user_id
        date:
            type: date
        image:
            type: string
            length: 255
            nullable: true
        path:
            type: string
            nullable: true
        content:
            type: text
        extract:
            type: text
        status:
            type: boolean
    lifecycleCallbacks: {  }
