SpljBundle\Entity\Mcq:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '100'
        theme:
            type: string
            length: '100'
        userId:
            type: integer
            column: user_id
        nbQuestions:
            type: integer
            column: nb_questions
        status:
            type: integer
    lifecycleCallbacks: {  }
