SpljBundle\Entity\Mcq:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '100'
        theme:
            type: string
            length: '100'
        status:
            type: boolean
    lifecycleCallbacks: {  }
