SpljBundle\Entity\Score:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
            type: integer
        mcqId:
            type: integer
        score:
            type: integer
        scoreMax:
            type: integer
    lifecycleCallbacks: {  }
