services:
#    splj.example:
#        class: SpljBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    redirect.after.login:
        class: UserBundle\Redirection\AfterLoginRedirection
        arguments: [@router,@doctrine]
    redirect.after.logout:
        class: UserBundle\Redirection\AfterLogoutRedirection
        arguments: [@router, @security.context]
